spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/stackoverflow
      username: root
      password:


jwt:
  secretKey: ehdals12341234123412341234123412341234
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 720

